### ISSUE TITLE
JSONView removed from Chrome store?

### ISSUE THREAD

**Issue by KingRider** [jamiew/jsonview-chrome#10]
What happen jsonview stopped chrome extension? Take no notice

**Comment by jamiew** [comment]
This repository is actually unrelated to the published JSONView extension in the Chrome store (with the security vulnerability). See #9. Sorry!

**Comment by jamiew** [comment]
This looks like the real repository (I think): https://github.com/gildas-lormeau/JSONView-for-Chrome/issues/75

I'm going to re-open this ticket in to pre-empt further issues

**Comment by KingRider** [comment]
@jamiew Thanks!
