### ISSUE TITLE
Quotes in links are not escaped, so the <a> tag's href is broken

### ISSUE THREAD

**Issue by Sense545** [jamiew/jsonview-chrome#4]
`{ "link": "http://www.google.com/?q=\"quotes\"" }`

produces

```
<div id="json">
  <div class="collapser"></div>{
  <span class="ellipsis"></span>
  <ul class="obj collapsible">
    <li>
      <div class="hoverable">
        <span class="property">link</span>: 
        <span class="type-string">"</span>
        <a href="http://www.google.com/?q=" quotes""="">
          http://www.google.com/?q="quotes"
        </a>
        <span class="type-string">"</span>
      </div>
    </li>
  </ul>}
</div>
```

href should be `"http://www.google.com/?q=&quot;quotes&quot;"`.
Now it is broken up into an incomplete url and an extra `quotes""` attribute.

**Comment by Sense545** [comment]
Changing jsonview.js:82

```
output += '<a href="' + value + '">' + this.htmlEncode(value) + '</a>';
```

into

```
var encodedValue = this.htmlEncode(value);
output += '<a href="' + encodedValue + '">' + encodedValue + '</a>';
```

would suffice i guess..

**Comment by jamiew** [comment]
@Sense545 – I haven't maintained this extension in a long time as there are more complete alternatives available.

That said I'd be happy to merge your patch and give you commit access if you were interested! Thanks
