### ISSUE TITLE
Removed from Chrome store?

### ISSUE THREAD

**Issue by avaer** [jamiew/jsonview-chrome#9]
@jamiew Was this removed from the Chrome store for some reason? At least, the link in the README.md doesn't work anymore: https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc.

**Comment by jamiew** [comment]
Per the README that extension is unrelated to this repository (which is unmaintained)

FWIW I think sure Chrome has JSON formatting and syntax highlighting built-in now

**Comment by avaer** [comment]
Thanks!
